export const hotelTypes = [
  "Budget",
  "International",
  "Admission",
  "Department",
  "Cultural",
  "Administration",
  // "Boutique",
  "Luxury",
  // "Ski Resort",
  "Business",
  "Family",
  // "Romantic",
  // "Hiking Resort",
  // "Cabin",
  // "Beach Resort",
  // "Golf Resort",
  // "Motel",
  // "All Inclusive",
  // "Pet Friendly",
  // "Self Catering",
];

export const hotelFacilities = [
  "Free WiFi",
  "Food & Drink",
  "Projector",
  "Whiteboard",
  "Flipchart",
  "Microphone",
  "Sound System",
  "Stage",
  "Dance Floor",
  "Lighting System",
  // "Parking",
  // "Airport Shuttle",
  // "Family Rooms",
  "Non-Smoking Rooms",
  // "Outdoor Pool",
  // "Spa",
  // "Fitness Center",
];
